utils::globalVariables(c(
  ".", ".data", "species", "var_type", "region_type", "gene", "frequency_per_kb",
  "variant_count", "region_length", "position", "genome_region", "region_name",
  "region_start", "region_end", "sample_id", "sample_count", "threshold",
  "is_potential_hotspot", "num_species", "mean_frequency", "gene_category",
  "functional_group", "gene_name", "gene_length", "cds_length", "total_variants",
  "Species", "Gene", "Type", "Minimum", "Maximum", "Length", "Intervals",
  "Name", "Region_Name", "Region_Type", "Start", "End",
  "zero_pattern", "count", "variable", "frequency", "snp", "INDEL", "total_sites",
  "snp_indel_ratio", "indel_sequence", "indel_type", "ref_allele", "alt_allele",
  "ref_length", "alt_length", "copy_count", "copy_index", "special_handling",
  "genome_structure_type", "group", "factor1", "factor2", "p.value", "p.adj",
  "Comparison", "Z", "P.unadj", "P.adj", "median_frequency", "sd_frequency",
  "analysis_entries", "entries", "groups", "variants", "start_position",
  "end_position", "poiGS_freq", "gene_freq_avg", "num_species_shared",
  "marker_shape", "Chr", "Start", "End", "Value", "color", "shape",
  "Type", "Name", "Parent", "ID", "width", "strand", "seqnames",
  "# Intervals", ":=", "Annotation", "CDS_length", "Correlation",
  "End_Position", "Maximum_raw", "Minimum_raw", "PC1", "PC1_rank", "PC2",
  "PC2_rank", "PC3", "PC3_rank", "Sequence Name", "Shape", "Species1",
  "Species2", "Start_Position", "V1", "V12", "V2", "V3", "V4", "V5", "V6",
  "avg_frequency", "category", "color_index", "combined_rank", "component",
  "coord_diff", "correlation", "coverage_rate", "covered_bases", "cumulative",
  "dataset", "deduplicated_variants", "dual_composite_file", "enrichment_ratio",
  "exon_count", "expected_count", "expected_in_sample", "filtered_IR",
  "filtered_IRA", "filtered_LSC", "filtered_RNA", "filtered_SSC",
  "filtered_variants", "filtered_variants_IRA_only",
  "filtered_variants_full_genome", "frequency_display",
  "functional_annotation", "functional_category", "gap_end", "gap_length",
  "gap_reason", "gap_size", "gap_start", "gaps_count", "gene1", "gene1_freq",
  "gene2", "gene2_freq", "gene_category_clean", "gene_category_final",
  "gene_end", "gene_events", "gene_frequency", "gene_id", "gene_pair",
  "gene_pair_raw", "gene_start", "has_intron_annotation", "hotspot_type",
  "indel_length", "intervals_count", "intron_number", "ir_start", "is_hotspot",
  "label", "label_text", "max_frequency", "max_length", "mean_freq",
  "mean_length", "median_length", "method", "mixed", "n_alleles",
  "n_deletions", "n_indels", "n_insertions", "n_length_1", "n_outliers",
  "n_samples", "n_sites", "n_species", "n_total", "n_unique_lengths",
  "n_unique_sequences", "neg_log_p", "next_max", "next_min", "next_name",
  "nonsynonymous", "observed_count", "observed_successes",
  "original_gene_pair", "original_variants", "overall_retention_rate",
  "p_adjusted", "p_value", "peak_x", "peak_y", "pearson_p", "pearson_r",
  "percentage", "poiGS_ID", "population_size", "present", "proportion",
  "reason", "region", "region_count", "report_base_path", "residual",
  "sample_size", "segment_length", "sig_fdr", "significance", "significant",
  "single_composite_file", "site_count", "site_type", "sn_ratio",
  "sorted_gene1", "sorted_gene2", "spearman_p", "spearman_r", "species_count",
  "species_count_for_hotspot", "species_list", "std_residual",
  "success_states_in_pop", "sufficient_data", "synonymous", "target_count",
  "total_count", "total_count_in_pie", "total_genome_length", "total_length",
  "total_region_length", "total_samples_at_site", "total_variant_count",
  "unfiltered_variants", "unfiltered_variants_ira_only", "value", "variance",
  "variant_class", "variants_in_gaps"
))
